codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "40...100"

ignore:
  - test
  - simulation

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: no
  after_n_builds: 2
