path_classifiers:
  test: "test/*.py"
extraction:
  cpp:
    prepare:
      packages:
      - libboost-all-dev
      - libssl-dev
      - ninja-build
    after_prepare: |
      wget -q "https://github.com/Kitware/CMake/releases/download/v3.21.2/cmake-3.21.2-linux-x86_64.tar.gz"
      tar xzf cmake-3.21.2-linux-x86_64.tar.gz
    index:
      build_command: |
         ./cmake-3.21.2-linux-x86_64/bin/cmake -Dbuild_examples=ON -Dbuild_tests=ON -Dbuild_tools=ON -GNinja .
         ./cmake-3.21.2-linux-x86_64/bin/cmake --build .
