test_dirs:
 - test

project:
 libtorrent

features:
 - variant=release asserts=production
 - statistics=on logging=verbose disk-stats=on bandwidth-limit-logging=on dht=logging
 - asserts=production ipv6=off dht=off extensions=off logging=off
 - deprecated-functions=off 

