test_dirs:
 - test

project: libtorrent

branch: trunk

clean:
 - test_tmp_*

time_limit: 500

features:
# - variant=release asserts=production
 - statistics=on logging=verbose disk-stats=on bandwidth-limit-logging=on dht=logging
# - asserts=production ipv6=off dht=off extensions=off logging=none
# - deprecated-functions=off 

