test_dirs:
 - test

project: libtorrent

branch: trunk

clean:
 - test_tmp_*

time_limit: 700

features:
 - variant=release asserts=production
 - encryption=openssl statistics=on logging=verbose disk-stats=on dht=logging request-log=on
 - ipv6=off dht=off extensions=off logging=none deprecated-functions=off 

