# all features are built in these directories
test_dirs:
 - test

features:
 - variant=release asserts=production debug-symbols=on
 - encryption=openssl statistics=on logging=verbose disk-stats=on dht=logging request-log=on allocator=debug debug-iterators=on

# all build_features are built in these directories
build_dirs:
 - tools
 - examples
 - bindings/python

build_features:
 - ipv6=off
 - deprecated-functions=off 
 - logging=verbose
 - statistics=on
 - asserts=off
 - asserts=production debug
 - asserts=on release
 - ipv6=off dht=off extensions=off logging=none deprecated-functions=off invariant-checks=off 

project: libtorrent

branch: aio

clean:
 - test_tmp_*

time_limit: 600

