name: clang-tidy

on:
   push:
      branches: [ RC_1_2 RC_2_0 master ]
   pull_request:

concurrency:
   group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
   cancel-in-progress: true

jobs:

   clang_tidy:
      name: clang-tidy
      runs-on: ubuntu-24.04

      steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
           submodules: true
           fetch-depth: 1
           filter: tree:0

      - name: update package lists
        continue-on-error: true
        run: |
          sudo apt update

      - uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ccache-linux-clang-tidy-${{ github.base_ref }}
          ccache_options: |
            max_size=500M

      - name: install clang-tidy-18
        run: sudo apt install clang-tidy libc++-dev

      - name: install boost
        run: |
          sudo apt install libboost-tools-dev libboost-dev
          echo "using clang_tidy : : clang-tidy : <cxxflags>-std=c++17 <cxxflags>-I/usr/local/clang-7.0.0/include/c++/v1 <cxxflags>-stdlib=libc++ <cxxflags>-Wno-unknown-warning-option <linkflags>-stdlib=libc++ ;" >> ~/user-config.jam;

      - name: analyze
        run: |
          b2 -a clang_tidy



